### ISSUE TITLE
Bug: Doesn't recognize div.CLASS_NAME as CLASS_NAME

### ISSUE THREAD

**Issue by wildeyes** [Quramy/typed-css-modules#28]
Selectors like `div.newsContainer` are not recognized by tcm, and don't get exported into the .d.ts.

**Comment by juanluispaz** [comment]
This error happens when I using the watch mode

Example:

Initially, the file component.css contains
```css
div.component {
    color: blue;
}

div.test {
    color: yellow;
}
```

If I run `tcm src -o src_gen -c -w`

The file component.css.d.ts is generated with:
```typescript
export const component: string;
export const test: string;

```

But, if then I change the component.css file to:
```css
div.component {
    color: blue;
}

.test {
    color: yellow;
}
```

An empty component.css.d.ts file is generated.

Even, if I change again the component.css file to:
```css
.component {
    color: blue;
}

.test {
    color: yellow;
}
```

An empty component.css.d.ts file is still generated.

But, if you close the tcm watch process and launch it again, it regenerate the file properly 

Note: I'm using typed-css-modules version 0.3.7
