### ISSUE TITLE
Definitions for classes named "default" are not created

### ISSUE THREAD

**Issue by cameron-martin** [Quramy/typed-css-modules#33]
If I have a CSS file like so

```css
.default {
  background-color: black;
}

.foo {
  color: white;
}
```

Then the d.ts files only contain definitions for `foo`.
